### ISSUE TITLE
default value for collectionThroughput is expensive

### ISSUE THREAD

**Issue by awangptc** [Azure/azure-cosmosdb-bulkexecutor-java-getting-started#5]
The default value of the collectionThroughput in this library is 1000000.  This results in a charge of $480/hr.  The default value within the Azure portal is 400.  Please change the default to a more reasonable value and perhaps document the impact of this.

**Comment by abinav2307** [comment]
Thanks for the suggestion. We just pushed out a change to lower the entry point from 1M to 100K. 

We left it at 100K as a significantly lower throughput would not highlight the performance benefits of the Bulk Executor.
